theme: jekyll-theme-cayman
description: ğŸğŸ„ Jaymie's 2018 Longform Birthday Adventure ğŸ’ªğŸ¥¨
title: Happy Birthday! 
CustomReturn: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
